#!/bin/bash

[ "${DSOCKS_VERSION-unset}" = "unset" ] && export DSOCKS_VERSION=5
[ "${DSOCKS_PROXY-unset}" = "unset" ] && export DSOCKS_PROXY="127.0.0.1:1080"

if [ `uname -s` = "Darwin" ]; then
  # for macOS
  [ "${DSOCKS_LIBRARY-unset}" = "unset" ] && DSOCKS_LIBRARY=/usr/local/lib/libdsocks-x.dylib
  DYLD_INSERT_LIBRARIES=$DSOCKS_LIBRARY DYLD_FORCE_FLAT_NAMESPACE=1 exec "$@"
else
  [ "${DSOCKS_LIBRARY-unset}" = "unset" ] && DSOCKS_LIBRARY=/usr/local/lib/libdsocks-x.so.1.0
  LD_PRELOAD=$DSOCKS_LIBRARY exec "$@"
fi
